### ISSUE TITLE
Make Sign-Up page check that passwords match

### ISSUE THREAD

**Issue by mattroseman** [mroseman95/Ingredient-Sharer#18]
Right now it isn't checking the passwords to see if they match or not.

**Comment by mattroseman** [comment]
Should do this on user side and on server side. So before submit, and before user is entered in database.

**Comment by hunj** [comment]
It's just ugly right now:
![image](https://cloud.githubusercontent.com/assets/3972717/19700199/64e3906c-9ac4-11e6-8cad-9c609d72a118.png)
