### ISSUE TITLE
sign up fields must have content before being submitted

### ISSUE THREAD

**Issue by mattroseman** [mroseman95/Ingredient-Sharer#20]
Make sure none of the fields are blank (email, password, password confirm)

**Comment by hunj** [comment]
OK we have a problem now. When a new user, in registration page, hits the [Submit] button with some fields blank, should it:
- Make the system deny, refresh the signup page with given alert notice message included, OR
- Try to warn user directly on page (i.e. popup)?

I think this is more of a frontend/backend kind of decision. Using the front-end (second solution) would be a great quickfix but it also means that we will have some hard time unit testing.

**Comment by mattroseman** [comment]
I kind of decided this without you. What I did is a separate validation stop from the password and email validation. I gave all the fields a required attribute, meaning you can't even attempt to submit the form without filling them out. A warning will pop up and tell you the field is required.
