### ISSUE TITLE
implement password requirements

### ISSUE THREAD

**Issue by mattroseman** [mroseman95/Ingredient-Sharer#22]
This includes a minimum length, set of available characters, certain types of characters must be present. (see software requirements document)

**Comment by hunj** [comment]
From SRS:

> The password will be required to be at least 6 characters long with special characters, uppercase and lowercase alphabets. 

Also relevant:

> Upon submitting the registration form with proper information, the user will be forwarded to the login page.

**Comment by hunj** [comment]
Use RegExp `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d). /` for detecting special characters, uppercase and lowercase alphabets. Length is checked via Devise settings.
